# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Standup < Formula
  desc "Terminal dashboard for Jira sprint issues and GitHub PRs across clients"
  homepage "https://github.com/jhonsanchez/standup"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.2/standup_0.6.2_darwin_amd64.tar.gz"
      sha256 "32d1a7a2dcc70ca6524ab7422294a4af997ff08f61871a54ec16d704944fdfef"

      define_method(:install) do
        bin.install "standup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.2/standup_0.6.2_darwin_arm64.tar.gz"
      sha256 "d3b91f59f4a9cfaa63c1c31bb038cff633e7349dd354ef0a0f2e2d80a0231a9c"

      define_method(:install) do
        bin.install "standup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.2/standup_0.6.2_linux_amd64.tar.gz"
      sha256 "db12fdd4ccc24d901cc9b93191b993928c019f6282264a00a78fb8017197d707"
      define_method(:install) do
        bin.install "standup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.2/standup_0.6.2_linux_arm64.tar.gz"
      sha256 "6fe5882f169ada6be2234adf5f1ee4f26c6caf5226d840d27ce86957fe7d819d"
      define_method(:install) do
        bin.install "standup"
      end
    end
  end

  def caveats
    <<~EOS
      Config lives at ~/.config/standup/config.yaml — a commented starter
      file is created the first time you run standup.

      Icons need a Nerd Font (e.g. JetBrainsMono Nerd Font):
        brew install --cask font-jetbrains-mono-nerd-font
      …or set `icons: ascii` in the config.

      Verify your setup any time with:  standup doctor
    EOS
  end

  test do
    system "#{bin}/standup --version"
  end
end
