# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Standup < Formula
  desc "Terminal dashboard for Jira sprint issues and GitHub PRs across clients"
  homepage "https://github.com/jhonsanchez/standup"
  version "0.6.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.7/standup_0.6.7_darwin_amd64.tar.gz"
      sha256 "8d0385b84bdd7a299789ddcefc27ae875f67d6e64005b46de31eb4e2d44f5b18"

      define_method(:install) do
        bin.install "standup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.7/standup_0.6.7_darwin_arm64.tar.gz"
      sha256 "cc455fb775232ff6c3af057809f900786944a3fe2a267e945cf0ab79c5f5fbb8"

      define_method(:install) do
        bin.install "standup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.7/standup_0.6.7_linux_amd64.tar.gz"
      sha256 "7f1f64818b78d3fce7fad7125580c3a55d733a6af940a525a600ace5880108b4"
      define_method(:install) do
        bin.install "standup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.6.7/standup_0.6.7_linux_arm64.tar.gz"
      sha256 "6086b0d6682e1665977fa6dfcc9cc26d66133c6cfc238a4ff4d5c5c20462214c"
      define_method(:install) do
        bin.install "standup"
      end
    end
  end

  def caveats
    <<~EOS
      Config lives at ~/.config/standup/config.yaml — a commented starter
      file is created the first time you run standup.

      Icons need a Nerd Font (e.g. JetBrainsMono Nerd Font):
        brew install --cask font-jetbrains-mono-nerd-font
      …or set `icons: ascii` in the config.

      Verify your setup any time with:  standup doctor
    EOS
  end

  test do
    system "#{bin}/standup --version"
  end
end
