# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Standup < Formula
  desc "Terminal dashboard for Jira sprint issues and GitHub PRs across clients"
  homepage "https://github.com/jhonsanchez/standup"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.7.1/standup_0.7.1_darwin_amd64.tar.gz"
      sha256 "5e899a2c216b88abec00554648060bf87e61b5260c7e47a87c46fd448b42fab5"

      define_method(:install) do
        bin.install "standup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.7.1/standup_0.7.1_darwin_arm64.tar.gz"
      sha256 "7e7cbeff6887658481e5b3954e712670b864f0efc8678f72b6981ba66db113cc"

      define_method(:install) do
        bin.install "standup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.7.1/standup_0.7.1_linux_amd64.tar.gz"
      sha256 "c9d122f3ad521109aed4ae7e9d43c2dab3fc16abbfc35ff29b768e68ce17a782"
      define_method(:install) do
        bin.install "standup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhonsanchez/standup/releases/download/v0.7.1/standup_0.7.1_linux_arm64.tar.gz"
      sha256 "53c5fd0759a0061378487e9e862ec05f476984a2ae58280a6ae52be55e182349"
      define_method(:install) do
        bin.install "standup"
      end
    end
  end

  def caveats
    <<~EOS
      Config lives at ~/.config/standup/config.yaml — a commented starter
      file is created the first time you run standup.

      Icons need a Nerd Font (e.g. JetBrainsMono Nerd Font):
        brew install --cask font-jetbrains-mono-nerd-font
      …or set `icons: ascii` in the config.

      Verify your setup any time with:  standup doctor
    EOS
  end

  test do
    system "#{bin}/standup --version"
  end
end
